# Generated by Django 5.1.5 on 2025-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(max_length=10, unique=True)),
                ('amount', models.IntegerField()),
                ('previous_balance', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
