# Generated by Django 5.1.5 on 2025-01-18 09:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='id',
            field=models.CharField(default=api.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
